recipe: default.v1
language: en
pipeline:
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    type: ollama # defaults to locally running ollama server
    model_name: finetuned_command_generator
  flow_retrieval:
      embeddings:
        type: "huggingface"
        model_name: "sentence-transformers/all-MiniLM-L6-v2"
        model_kwargs:
          device: "cpu"
        encode_kwargs:
          normalize_embeddings: True
      active: true
      num_flows: 10

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:
    type: ollama # defaults to locally running ollama server
    model_name: finetuned_command_generator
  embeddings:
        type: "huggingface"
        model_name: "sentence-transformers/all-MiniLM-L6-v2"
        model_kwargs:
          device: "cpu"
        encode_kwargs:
          normalize_embeddings: True

assistant_id: 20240418-073244-narrow-archive
