recipe: default.v1
language: en
pipeline:
# - name: LLMBasedRouter
#   calm_entry:
#     sticky: "handles everything else"
#   nlu_entry:
#     sticky: "handles everything around booking a hotel or a restaurant and health advice"
#     non_sticky: "handles chitchat"
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: LogisticRegressionClassifier
- name: CRFEntityExtractor
- name: DucklingEntityExtractor
  url: "http://duckling.gstephens.org"
  dimensions: [ "time", "number" ]
  timezone: "Americas/Los_Angeles"
  timeout: 3
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7
    temperature: 0.0
    top_p: 0.0

policies:
- name: RulePolicy
- name: TEDPolicy
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy

assistant_id: 20240418-073244-narrow-archive
