recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy

#  - name: RulePolicy
assistant_id: 20240130-202844-tractable-nut
