recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: custom_components.multi_step_llm_command_generator.MultiStepLLMCommandGenerator
  refine_slots: False
  stronger_llm:
    model: gpt-3.5-turbo
#    model: Llama-3-70b-chat-hf
    prompts:
      - refine_slot
  weaker_llm:
    model: gpt-3.5-turbo
    prompts:
      - fill_slots_for_newly_started_flow
      - fill_slots_of_current_flow
      - start_or_end_flows
  flow_retrieval:
    active: false
#- name: LLMCommandGenerator
#  llm:
#    model: gpt-4
#  flow_retrieval:
#    active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy
assistant_id: 20240429-160832-red-eagle
