recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7
    temperature: 0.0
    top_p: 0.0

policies:
- name: rasa.core.policies.flow_policy.FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy

#  - name: RulePolicy
assistant_id: 20240415-224149-ebony-charge
