recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: custom_components.multi_step_llm_command_generator.MultiStepLLMCommandGenerator
  strong_llm:
    model: Llama-3-70b-chat-hf
#    model: gpt-3.5-turbo
#    model: gpt-4
  weaker_llm:
    model: Llama-3-70b-chat-hf
#    model: gpt-3.5-turbo
#    model: gpt-4
  flow_retrieval:
    active: false
#- name: LLMCommandGenerator
#  llm:
#    model: gpt-4
#  flow_retrieval:
#    active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy
assistant_id: 20240429-160832-red-eagle
