recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: custom_components.multi_step_llm_command_generator.MultiStepLLMCommandGenerator
  llm:
    model: gpt-3.5-turbo
  prompts:
    start_or_end_flow:
      file_path: "/Users/ognjenfrancuski/Projects/rasa/rasa-calm-demo/custom_components/start_or_end_flows_prompt.jinja2"
    fill_slots:
      file_path: "/Users/ognjenfrancuski/Projects/rasa/rasa-calm-demo/custom_components/fill_slots_prompt.jinja2"
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy
assistant_id: 20240429-160832-red-eagle
