version: '3.8'

services:

 prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=otlp-write-receiver'
    ports:
      - "9090:9090"

 grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

 jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "14269:14269"
      - "4317"
    healthcheck:
      test: ["CMD", "wget", "http://0.0.0.0:14269"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - COLLECTOR_OTLP_ENABLED=true

 assistant:
    image: rasa/rasa:localdev
    volumes:
      - .:/app
    command:
      - 'inspect'
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      otlp-collector:
        condition: service_started

 otlp-collector:
   image: otel/opentelemetry-collector:latest
   volumes:
     - ./collector-config.yaml:/etc/otelcol/config.yaml
   ports:
     - "4317:4317" # otlp grpc receiver
     - "8888:8888" # Prometheus' metrics exposed by the collector
     - "8889:8889" # Prometheus exporter configured metrics
   depends_on:
     jaeger:
       condition: service_healthy

volumes:
 grafana_data:
