services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/rasa:cached
    command: sleep infinity
    ports:
      - "5005:5005"  # Rasa
      - "5055:5055"  # Rasa Action Server

  duckling:
    restart: unless-stopped
    image: "rasa/duckling:0.2.0.2"
    expose:
      - "8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage:Z
    ports:
      - "6333:6333"
      - "6334:6334"