recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model: gpt-4
    timeout: 7
    temperature: 0.0
    top_p: 0.0
  prompt_template: templates/command-generator.jinja2

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy

assistant_id: 20240418-073244-narrow-archive
