recipe: default.v1
language: en
pipeline:
- name: NLUCommandAdapter
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: openai-direct-gpt-4

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
- name: IntentlessPolicy

assistant_id: 20240418-073244-narrow-archive
